### ISSUE TITLE
Add ability to add lines of text to a button

### ISSUE THREAD

**Issue by LazyHatGuy** [koriwi/freedeck-configurator#23]
Instead of picking individual keystrokes, use a text box to add a string of text as a shortcut

**Comment by aukrausmi** [comment]
another vote for this, and extend the character limit from 8 to maybe 32 to allow long words or phrases - please, thank you :)

**Comment by koriwi** [comment]
the develop branch more or less has this now (you first have to update your arduino to develop branch, too)
it still displays as individual keystrokes because it also shows you shift, ctrl etc which will also take away a slot from your 15 available keystrokes now. i cant increase the limit without breaking compatibility with old config files
