### ISSUE TITLE
add a time out for OLEDs after now use and wake on press

### ISSUE THREAD

**Issue by aukrausmi** [koriwi/freedeck-configurator#28]
OLEDs are pretty bad for burn in and if we could have a timeout setting that would be good for our displays

**Comment by legomannetje** [comment]
timeout is implemented in V2.0 of the ino. This can be closed @koriwi

**Comment by koriwi** [comment]
I will keep this open because i want to implement the timeout to be changeable in the configurator. But as @legomannetje said it is implemented in the firmware and can be configured in the settings.h

**Comment by koriwi** [comment]
https://github.com/FreeYourStream/freedeck-configurator/issues/35

**Comment by IAmOrion** [comment]
This function is active, but bugged.  FW 2.3.0 sleeps after 5-10 seconds regardless of what is set in the configurator.  I will copy this to the FreeDeck ino issues too (Since I imagine the problem is actually part of the Arduino Code)

FW 2.3.0
FreeDeck Configurator
Version: 2.0.0
Build: 1657321297191
Commit: 6714d6c
